import React from 'react';
// import Head from 'next/head'
// import Image from 'next/image

// import imageHeader from '/src/img/exampleImageHeader.jpg';
import { AppContext } from "/src/context/AppContext";
import imgCard from '/src/img/carImg.jpg';

import { HeroHeader } from "/src/templates/HeroHeader";
import { TrendingCarrusel } from "/src/templates/TrendingCarrusel";
import { SearchGridCard } from "/src/templates/SearchGridCard";
import { RightBarModal } from "/src/templates/RightBarModal";

export default function Home() {
  const {trendingMovies} = React.useContext(AppContext);
  const imageHeader = `https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/${trendingMovies[0]?.poster_path}`;

  return (
    <div className="w-full h-full bg-white dark:bg-darkModeColor  dark:text-white
      sm:min-w-[320px]">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <HeroHeader 
        h1_title={'MovieApp'}
        imageHeader={imageHeader}
      />

      <main className="relative z-30 pt-5 pb-5 bg-white dark:bg-version2 flex flex-col items-center">

        <div className="w-[95%]">
          <TrendingCarrusel />
        </div>

        <div id='SearchGridCard' className="w-[95%] mt-5">
          <SearchGridCard />
        </div>
        
        <RightBarModal />
        
      </main>
    </div>
  )
}
